name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  armvirt_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get secret key
      run: 'echo "$SECRET_KEY" > secrets.key'
      shell: bash
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
    - name: Build ipk
      run: ./build.sh https://downloads.openwrt.org/releases/22.03.0-rc5/targets/armvirt/64/openwrt-sdk-22.03.0-rc5-armvirt-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz armvirt_64

    - name: Save ipk
      uses: actions/upload-artifact@v1
      with:
          name: armvirt_64
          path: target.zip
