name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ramips-mt7620:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build ipk
      run: ./build.sh https://downloads.openwrt.org/releases/19.07.3/targets/ramips/mt7620/openwrt-sdk-19.07.3-ramips-mt7620_gcc-7.5.0_musl.Linux-x86_64.tar.xz ramips/mt7620

    - name: Save ipk
      uses: actions/upload-artifact@v1
      with:
          name: ramips-mt7620
          path: target-ramips-mt7620.zip

  ramips-mt7621:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build ipk
      run: ./build.sh https://downloads.openwrt.org/releases/19.07.3/targets/ramips/mt7621/openwrt-sdk-19.07.3-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64.tar.xz ramips/mt7621

    - name: Save ipk
      uses: actions/upload-artifact@v1
      with:
          name: ramips-mt7621
          path: target-ramips-mt7621.zip